swagger: '2.0'
info:
  title: Indri Suite
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
basePath: /api/v1
paths:
  /search:
    post:
      tags: [Search]
      operationId: indri_suite.api.search.post
      summary: Send a query to Indri and get the response
      parameters:
        - name: request
          in: body
          schema:
            type: object
            required:
              - query
              - settings
            properties:
              query:
                type: string
                description: An Indri query.
                example: "#combine(he she)"
              settings:
                $ref: '#/definitions/Settings'
        - in: query
          name: size
          type: integer
          description: The numbers of items to return.
          minimum: 1
          maximum: 1000
          default: 50
        - in: query
          name: page
          type: integer
          description: Current page.
          minimum: 0
          default: 0
      responses:
        200:
          description: Return a list of the found documents.
          schema:
            $ref: '#/definitions/SearchResponse'
        400:
          description: No results were found.
          schema:
            type: string
            description: The error message.

  /evaluate:
    post:
      tags: [Evaluate]
      operationId: indri_suite.api.evaluate.post
      summary: Send a query to Indri and evaluate it againat the qrels.
      parameters:
        - name: request
          in: body
          schema:
            type: object
            required:
              - query
              - query_id
              - settings
            properties:
              query:
                type: string
                description: An Indri query.
                example: "#combine(he she)"
              query_id:
                type: string
                description: The ID of the query.
                example: "23"
              settings:
                $ref: '#/definitions/Settings'
      responses:
        200:
          description: Return an evaluation summary.
          schema:
            $ref: '#/definitions/EvaluationResponse'
        400:
          description: No results were found.
          schema:
            type: string
            description: The error message.

definitions:
  Settings:
    type: object
    required:
      - index_path
      - corpus_path
    properties:
      index_path:
        type: string
        description: Filepath to the index directory.
        example: "/nobackup/gontrum/ir/lab2/GH95_index/"
      corpus_path:
        type: string
        description: Filepath to the folder of the extracted corpus.
        example: "/nobackup/gontrum/ir/lab2/GH95/"
      gold_eval_path:
        type: string
        description: Filepath to the gold file.
        example: "/nobackup/gontrum/ir/lab2/AH-ENGLISH-CLEF2006.txt"

  DocumentReference:
    type: object
    properties:
      query_id:
        type: string
        example: "Q0"
      document_id:
        type: string
        example: "GH951020-000134"
      document:
        type: string
        description: The actual document, including XML tags.
        example: "Lot's of XML text."
      score:
        type: number
        description: The search rating of this document.
        example: -4.6095
      index:
        type: number
        description: The position of the search result.
        example: 1

  SearchResponse:
    type: object
    properties:
      size:
        type: number
      documents:
        type: array
        items:
          $ref: '#/definitions/DocumentReference'

  EvaluationResponse:
    type: object
    properties:
      raw_eval_output:
        type: string
        description: The whole output from trec_eval
      eval:
        type: object
        description: Structured output from trec_eval
        properties:
          num:
            type: number
      relevant_documents:
        description: The relevant gold documents.
        type: array
        items:
          $ref: '#/definitions/DocumentReference'
      retrieved_documents:
        description: The first retrieved documents.
        type: array
        items:
          $ref: '#/definitions/DocumentReference'
      relevant_retrieved:
        description: Relevant documents that were retrieved.
        type: array
        items:
          $ref: '#/definitions/DocumentReference'
      missing_relevant_documents:
        description: A list of document ids that are not present in the corpus.
        type: array
        items:
          type: string
          description: Id of a document